# Generated by Django 3.1.2 on 2020-10-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPU', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='realprice',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
